parameters:
  TargetProjects: 'src/**/*.csproj'
jobs:
- job: CodeBuild
  pool:
    name: SLD Build pool
    #demands: LATEST_DOTNET_VERSION
  variables:
  - group: BUILD Management Resources
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: ${{ parameters.TargetProjects }}
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  - task: NuGetCommand@2
    displayName: Restore
    inputs:
      command: restore
      projects: ${{ parameters.TargetProjects }}
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'
    
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  ${{ parameters.TargetProjects }}
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: "Publish SFA.DAS.Payments.EarningEvents.Domain"
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/SFA.DAS.Payments.EarningEvents.Domain/SFA.DAS.Payments.EarningEvents.Domain.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish SFA.DAS.Payments.EarningEvents.Messages"
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/SFA.DAS.Payments.EarningEvents.Messages/SFA.DAS.Payments.EarningEvents.Messages.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish SFA.DAS.Payments.EarningEvents.Messages.Internal"
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/SFA.DAS.Payments.EarningEvents.Messages.Internal/SFA.DAS.Payments.EarningEvents.Messages.Internal.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/publish'
    inputs:
      Contents: |
       /**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: drop'
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: drop

  - template: /azure-pipelines-templates/build/step/nuget-pack.yml
    parameters:
      DotNetStandardPackagesToPack: |
         src/SFA.DAS.Payments.EarningEvents.Domain/SFA.DAS.Payments.EarningEvents.Domain.csproj;
         src/SFA.DAS.Payments.EarningEvents.Messages/SFA.DAS.Payments.EarningEvents.Messages.csproj;
         src/SFA.DAS.Payments.EarningEvents.Messages.Internal/SFA.DAS.Payments.EarningEvents.Messages.Internal.csproj;
        