@gslApprenticeship
Feature: GSL Apprenticeship On-Programme Payments

PV2-4194 / PV2-4230
As the Payments Service
I want to process earnings generated by the DAS Earnings Calculator for On-Programme and Incentive payments
So that the service can make the necessary payments to providers



Scenario: Basic day on-programme payments - ACT1 - Same academic year
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type | Amount |
		| 2526           | 1                | Learning      | 1000   |
		| 2526           | 2                | Learning      | 1000   |
		| 2526           | 3                | Learning      | 1000   |
		| 2526           | 4                | Learning      | 1000   |
		| 2526           | 5                | Learning      | 1000   |
		| 2526           | 6                | Learning      | 1000   |
		| 2526           | 7                | Learning      | 1000   |
		| 2526           | 8                | Learning      | 1000   |
		| 2526           | 9                | Learning      | 1000   |
		| 2526           | 10               | Learning      | 1000   |
		| 2526           | 11               | Learning      | 1000   |
		| 2526           | 12               | Learning      | 1000   |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R01                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type | Amount |
		| R01                | 2526           | 1                | Learning          | 1000   |
		| R01                | 2526           | 2                | Learning          | 1000   |
		| R01                | 2526           | 3                | Learning          | 1000   |
		| R01                | 2526           | 4                | Learning          | 1000   |
		| R01                | 2526           | 5                | Learning          | 1000   |
		| R01                | 2526           | 6                | Learning          | 1000   |
		| R01                | 2526           | 7                | Learning          | 1000   |
		| R01                | 2526           | 8                | Learning          | 1000   |
		| R01                | 2526           | 9                | Learning          | 1000   |
		| R01                | 2526           | 10               | Learning          | 1000   |
		| R01                | 2526           | 11               | Learning          | 1000   |
		| R01                | 2526           | 12               | Learning          | 1000   |
	And all learner details, training details and payment details match the values on the incoming message
	And the incoming earnings have been saved in the Earnings Bridge cache tables

Scenario: Basic day on-programme payments - ACT1 - Split academic year: one open, one not open
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type | Amount |
		| 2526           | 3                | Learning      | 1000   |
		| 2526           | 4                | Learning      | 1000   |
		| 2526           | 5                | Learning      | 1000   |
		| 2526           | 6                | Learning      | 1000   |
		| 2526           | 7                | Learning      | 1000   |
		| 2526           | 8                | Learning      | 1000   |
		| 2526           | 9                | Learning      | 1000   |
		| 2526           | 10               | Learning      | 1000   |
		| 2526           | 11               | Learning      | 1000   |
		| 2526           | 12               | Learning      | 1000   |
		| 2627           | 1                | Learning      | 1000   |
		| 2627           | 2                | Learning      | 1000   |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R03                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type | Amount |
		| R03                | 2526           | 3                | Learning          | 1000   |
		| R03                | 2526           | 4                | Learning          | 1000   |
		| R03                | 2526           | 5                | Learning          | 1000   |
		| R03                | 2526           | 6                | Learning          | 1000   |
		| R03                | 2526           | 7                | Learning          | 1000   |
		| R03                | 2526           | 8                | Learning          | 1000   |
		| R03                | 2526           | 9                | Learning          | 1000   |
		| R03                | 2526           | 10               | Learning          | 1000   |
		| R03                | 2526           | 11               | Learning          | 1000   |
		| R03                | 2526           | 12               | Learning          | 1000   |
	And all learner details, training details and payment details match the values on the incoming message
	And the incoming earnings have been saved in the Earnings Bridge cache tables

Scenario: Basic day on-programme payments - ACT1 - Split academic year: both AYs open
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type | Amount |
		| 2526           | 11               | Learning      | 1000   |
		| 2526           | 12               | Learning      | 1000   |
		| 2627           | 1                | Learning      | 1000   |
		| 2627           | 2                | Learning      | 1000   |
		| 2627           | 3                | Learning      | 1000   |
		| 2627           | 4                | Learning      | 1000   |
		| 2627           | 5                | Learning      | 1000   |
		| 2627           | 6                | Learning      | 1000   |
		| 2627           | 7                | Learning      | 1000   |
		| 2627           | 8                | Learning      | 1000   |
		| 2627           | 9                | Learning      | 1000   |
		| 2627           | 10               | Learning      | 1000   |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R13                | 2526           |
		| R01                | 2627           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Events are published
		| Collection Period | Academic Year | Delivery Period | Transaction Type | Amount |
		| R13                | 2526           | 11               | Learning          | 1000   |
		| R13                | 2526           | 12               | Learning          | 1000   |
		| R01                | 2627           | 1                | Learning          | 1000   |
		| R01                | 2627           | 2                | Learning          | 1000   |
		| R01                | 2627           | 3                | Learning          | 1000   |
		| R01                | 2627           | 4                | Learning          | 1000   |
		| R01                | 2627           | 5                | Learning          | 1000   |
		| R01                | 2627           | 6                | Learning          | 1000   |
		| R01                | 2627           | 7                | Learning          | 1000   |
		| R01                | 2627           | 8                | Learning          | 1000   |
		| R01                | 2627           | 9                | Learning          | 1000   |
		| R01                | 2627           | 10               | Learning          | 1000   |
	And all learner details, training details and payment details match the values on the incoming message
	And the incoming earnings have been saved in the Earnings Bridge cache tables

Scenario: On-programme Completion and Balancing earnings are mapped as their own earning types
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type | Amount |
		| 2526           | 1                | Learning      | 700    |
		| 2526           | 1                | Completion    | 500    |
		| 2526           | 12               | Balancing     | 300    |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R01                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type | Amount |
		| R01                | 2526           | 1                | Learning          | 700    |
		| R01                | 2526           | 1                | Completion        | 500    |
		| R01                | 2526           | 12               | Balancing         | 300    |
	And all learner details, training details and payment details match the values on the incoming message
	And the incoming earnings have been saved in the Earnings Bridge cache tables

Scenario: 16 to 18 incentive and framework uplift earnings are mapped as incentive earnings
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type                    | Amount |
		| 2526           | 1                | Learning                        | 700    |
		| 2526           | 1                | First16To18EmployerIncentive     | 500    |
		| 2526           | 1                | First16To18ProviderIncentive     | 500    |
		| 2526           | 6                | Second16To18EmployerIncentive    | 500    |
		| 2526           | 6                | Second16To18ProviderIncentive    | 500    |
		| 2526           | 1                | OnProgramme16To18FrameworkUplift | 200    |
		| 2526           | 2                | Completion16To18FrameworkUplift  | 200    |
		| 2526           | 12               | Balancing16To18FrameworkUplift   | 200    |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R01                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type                 | Amount |
		| R01                | 2526           | 1                | Learning                         | 700    |
		| R01                | 2526           | 1                | First16To18EmployerIncentive      | 500    |
		| R01                | 2526           | 1                | First16To18ProviderIncentive      | 500    |
		| R01                | 2526           | 6                | Second16To18EmployerIncentive     | 500    |
		| R01                | 2526           | 6                | Second16To18ProviderIncentive     | 500    |
		| R01                | 2526           | 1                | OnProgramme16To18FrameworkUplift  | 200    |
		| R01                | 2526           | 2                | Completion16To18FrameworkUplift   | 200    |
		| R01                | 2526           | 12               | Balancing16To18FrameworkUplift    | 200    |
	And all learner details, training details and payment details match the values on the incoming message

Scenario: Disadvantage, learning support and care leaver incentive earnings are mapped as incentive earnings
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type               | Amount |
		| 2526           | 1                | Learning                   | 700    |
		| 2526           | 1                | FirstDisadvantagePayment    | 300    |
		| 2526           | 6                | SecondDisadvantagePayment   | 300    |
		| 2526           | 1                | LearningSupport             | 150    |
		| 2526           | 1                | CareLeaverApprenticePayment | 100    |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R01                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type            | Amount |
		| R01                | 2526           | 1                | Learning                    | 700    |
		| R01                | 2526           | 1                | FirstDisadvantagePayment     | 300    |
		| R01                | 2526           | 6                | SecondDisadvantagePayment    | 300    |
		| R01                | 2526           | 1                | LearningSupport              | 150    |
		| R01                | 2526           | 1                | CareLeaverApprenticePayment  | 100    |
	And all learner details, training details and payment details match the values on the incoming message

Scenario: Unsupported earning types are excluded from the outgoing earnings event
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type               | Amount |
		| 2526           | 1                | Learning                   | 700    |
		| 2526           | 1                | OnProgrammeMathsAndEnglish  | 250    |
		| 2526           | 12               | BalancingMathsAndEnglish    | 250    |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R01                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type | Amount |
		| R01                | 2526           | 1                | Learning          | 700    |
	And the outgoing GSL Apprenticeship Earnings Event maps 1 earning period in total
