@gslApprenticeship
Feature: GSL Apprenticeship Additional Payments

PV2-4230
As the Payments Service
I want to process earnings generated by the DAS Earnings Calculator for Additional Payments
So that the service can make the necessary payments to providers



Scenario: 16 to 18 incentive and framework uplift earnings are mapped as incentive earnings
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type                    | Amount |
		| 2526           | 1                | Learning                        | 700    |
		| 2526           | 1                | First16To18EmployerIncentive     | 500    |
		| 2526           | 1                | First16To18ProviderIncentive     | 500    |
		| 2526           | 6                | Second16To18EmployerIncentive    | 500    |
		| 2526           | 6                | Second16To18ProviderIncentive    | 500    |
		| 2526           | 1                | OnProgramme16To18FrameworkUplift | 200    |
		| 2526           | 2                | Completion16To18FrameworkUplift  | 200    |
		| 2526           | 12               | Balancing16To18FrameworkUplift   | 200    |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R01                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type                 | Amount |
		| R01                | 2526           | 1                | Learning                         | 700    |
		| R01                | 2526           | 1                | First16To18EmployerIncentive      | 500    |
		| R01                | 2526           | 1                | First16To18ProviderIncentive      | 500    |
		| R01                | 2526           | 6                | Second16To18EmployerIncentive     | 500    |
		| R01                | 2526           | 6                | Second16To18ProviderIncentive     | 500    |
		| R01                | 2526           | 1                | OnProgramme16To18FrameworkUplift  | 200    |
		| R01                | 2526           | 2                | Completion16To18FrameworkUplift   | 200    |
		| R01                | 2526           | 12               | Balancing16To18FrameworkUplift    | 200    |
	And all learner details, training details and payment details match the values on the incoming message

Scenario: Disadvantage, learning support and care leaver incentive earnings are mapped as incentive earnings
	Given the payments service receives a CalculateGrowthAndSkillsPayments event for apprenticeship payments
	And the event contains the following earnings
		| Academic Year | Delivery Period | Earning Type               | Amount |
		| 2526           | 1                | Learning                   | 700    |
		| 2526           | 1                | FirstDisadvantagePayment    | 300    |
		| 2526           | 6                | SecondDisadvantagePayment   | 300    |
		| 2526           | 1                | LearningSupport             | 150    |
		| 2526           | 1                | CareLeaverApprenticePayment | 100    |
	And the following collection periods are open
		| Collection Period | Academic Year |
		| R01                | 2526           |
	When the event is processed
	Then the following outgoing GSL Apprenticeship Earnings Event is published
		| Collection Period | Academic Year | Delivery Period | Transaction Type            | Amount |
		| R01                | 2526           | 1                | Learning                    | 700    |
		| R01                | 2526           | 1                | FirstDisadvantagePayment     | 300    |
		| R01                | 2526           | 6                | SecondDisadvantagePayment    | 300    |
		| R01                | 2526           | 1                | LearningSupport              | 150    |
		| R01                | 2526           | 1                | CareLeaverApprenticePayment  | 100    |
	And all learner details, training details and payment details match the values on the incoming message
